"""add deleted_at field to users

Revision ID: 07daed10f58b
Revises: b7b7642eb47f
Create Date: 2025-01-16 06:48:46.230381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07daed10f58b'
down_revision = 'b7b7642eb47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.drop_constraint('unique_post_view', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_post_view', ['post_id', 'user_id', 'ip_address'])

    # ### end Alembic commands ###
