"""add field

Revision ID: 20315b11c503
Revises: f3360e085d5b
Create Date: 2025-01-14 17:10:05.626289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20315b11c503'
down_revision = 'f3360e085d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
