"""add school college department to posts

Revision ID: 470eafa91a73
Revises: a40e3a1cd0e3
Create Date: 2025-01-14 16:56:15.333008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470eafa91a73'
down_revision = 'a40e3a1cd0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('college_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'colleges', ['college_id'], ['id'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')
        batch_op.drop_column('college_id')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
