"""rename anonymous_nickname to nickname in post_comments

Revision ID: 4ae991520c19
Revises: 424be806a023
Create Date: 2025-01-22 16:39:33.977528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae991520c19'
down_revision = '424be806a023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=False))
        batch_op.drop_column('anonymous_nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonymous_nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
