"""change is_deleted to deleted_at in posts and comments

Revision ID: ae519dc4f0c3
Revises: 4c1392fa6e5a
Create Date: 2025-01-24 14:56:35.626220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae519dc4f0c3'
down_revision = '4c1392fa6e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('register_type',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='usertype'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('register_type',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='usertype'),
               nullable=True)

    # ### end Alembic commands ###
