"""rename_post_view_counts_to_post_views_and_add_ip_address

Revision ID: ebdcebe2cab2
Revises: bc0bc293f04d
Create Date: 2025-01-14 21:08:33.610044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebdcebe2cab2'
down_revision = 'bc0bc293f04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', 'ip_address', name='unique_post_view')
    )
    op.drop_table('post_view_counts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_view_counts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_view_counts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_view_counts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_view_counts_pkey'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_view_count')
    )
    op.drop_table('post_views')
    # ### end Alembic commands ###
